export const ADDITION = 'ADDITION';
export const SUBSTACTION = 'SUBSTACTION';
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const ONLINE_USERLIST_CHANGED = 'ONLINE_USERLIST_CHANGED'
export const MESSAGE_UPDATE = "MESSAGE_UPDATE";
export const UPDATE_INFO = "UPDATE_INFO";
export const INSERT_NEW_MESSAGE = "INSERT_NEW_MESSAGE"